#ifndef CONFIG_HPP
#define CONFIG_HPP

//#define IMPEDANCES_IMPEDANCE_APPROACH
//#define IMPEDANCES_ADMITTANCE_APPROACH
#define IMPEDANCES_GMATRIX_APPROACH

//#define NPORT_ZMATRIX
#define NPORT_YMATRIX

#endif // CONFIG_HPP
